### ISSUE TITLE
Uniformizar a apresentação de salas e categorias com recursos

### ISSUE THREAD

**Issue by marcelomodesto** [uspdev/salas#109]
No menu administração -> recursos, o sistema apresenta os recursos cadastrados e dá a opção de cadastrar novos itens ou excluir os existentes. Acredito que para salas e categorias a exibição deveria ser da mesma maneira. Não?

**Comment by alecostaweb** [comment]
Sim

**Comment by alecostaweb** [comment]
Estamos implementando algumas coisas e isso vai pra fila também
