### ISSUE TITLE
Adicionar tratamento de erro para sala que não tem nenhuma reserva cadastrada

### ISSUE THREAD

**Issue by marcelomodesto** [uspdev/salas#110]
Ao tentar visualizar uma sala que não tem nenhuma reserva cadastrada para ela, o sistema lança a exceção que precisa ser tratada: 

Undefined variable: eventos 
app/Http/Controllers/SalaController.php:94

**Comment by alecostaweb** [comment]
@kawanks se puder priorizar essa
