### ISSUE TITLE
Cancelamento de uma reserva sem obrigatoriamente cancelar todas as recorrentes

### ISSUE THREAD

**Issue by marcelomodesto** [uspdev/salas#112]
Seria interessante se uma ou mais reservas pudessem ser cancelada sem obrigatoriamente ter que cancelar todas as reservas recorrentes associadas a ela. Há situações excepcionais, por exemplo, em que uma aula é cancelada somente em um dia ou a aula é dada em outro local.

**Comment by alecostaweb** [comment]
#96
